spring:
    application:
        name: mercadinhoastro

    datasource:
        url: jdbc:postgresql://localhost:5432/mercadinhoastro
        username: postgres
        password: 1234
        driver-class-name: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

    flyway:
        enabled: true